import type { Metadata } from "next";
import { Open_Sans } from "next/font/google"
import "./globals.css";
import { QueryProvider } from "@/providers/QueryProvider";
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <QueryProvider>
      <html
        lang="en"
        className={`${openSans.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </QueryProvider>
  );
}
